Replace GDAL with Apache SIS
pole-surfaces-planetaires/planet_crs_registry pull request #9
Opened 2024-04-29 07:57 UTC by alexismanin

Replace on-the-fly call to Gdal for GML generation. Instead, the server now serve pre-built GML files.

The GML files can be created using a GML generator program that takes a list of WKTs as input.
Apache SIS is used instead of GDAL.

2024-05-15 05:27 UTC, J-Christophe requested changes

2024-05-15 05:27 UTC, J-Christophe commented on templates/formula.html
peux-tu modifier : 
- Copyright 2021-2002. CNES (Jean-Christophe Malapert for PDSSP) en Copyright 2021-2024. CNES (Geomatys for PDSSP) ou quelque chose d'équivalent
- peux-tu stp remplacer Copyright 2021-2002 en Copyright 2021-2024 dans tous les fichiers (c'est une typo)

Le lien http dans cette page n'est pas visible à cause d'une CSS. c'est possible de le rendre explicite seulement pour cette page ?

2024-05-15 05:27 UTC, J-Christophe commented on tests/urls.sh
ce n'est pas "http://localhost:8080/ws/formula.html" mais http://localhost:8080/web/formula.html

2024-05-15 05:27 UTC, J-Christophe commented on data/gml_generator.py
Erreur lorsque j'exécute le script : 

(planet_crs_registry-env) malapert@JC-HP-ZBook-15-G4:~/Work/planet_crs_registry/data$ python gml_generator.py
  File "/home/malapert/Work/planet_crs_registry/data/gml_generator.py", line 482
    logging.debug(f"{path_to_file} // WKT: {wkt.split('\n')[0]}")
                                                                ^
SyntaxError: f-string expression part cannot include a backslash

(planet_crs_registry-env) malapert@JC-HP-ZBook-15-G4:~/Work/planet_crs_registry$ python --version
Python 3.10.12

2024-05-15 05:27 UTC, J-Christophe commented on Makefile
Pourrais-tu ajouter une tâche dans le Makefile pour automatiser la génération des GML ?

2024-05-15 05:27 UTC, J-Christophe commented on requirements.txt
les dépendances pour la génération des GML (JPype1 et tqdm) ne devraient-ils pas être ici pour l'installation ?

Le Dockerfile fait un "make", ce qui installe les dépendances. Sans JPype1 et tqdm, le script ne va pas fonctionner, n'est-ce pas ?

2024-05-15 08:50 UTC, Emile-Muller commented on templates/formula.html
Copyright mis à jour: abf70ed50d850a8ed2b40592e8c108b9e23c24f8

2024-05-15 09:32 UTC, Emile-Muller commented on templates/formula.html
Design/CSS du lien sur `formula.html` mise à jour: [d57bca3](https://github.com/pdssp/planet_crs_registry/pull/9/commits/d57bca3c047243019e7aeb80c597b5a1100823f4)

2024-05-15 09:45 UTC, Emile-Muller commented on tests/urls.sh
URL mis à jour: 8398e0a2e81a5c05836934491f5072de55afb806

2024-05-15 13:16 UTC, Emile-Muller commented on data/gml_generator.py
Problème de Python 3.10 réglé : f24fec15849c2c14217bef0fd6e2a139c57777b4

2024-05-15 13:16 UTC, Emile-Muller commented on Makefile
Tâche dans le Makefile ajoutée: f24fec15849c2c14217bef0fd6e2a139c57777b4

`make generate-gml`

2024-05-15 13:17 UTC, Emile-Muller commented on requirements.txt
Tâche dans le Makefile et `requirements_gml.txt` ajoutés: f24fec15849c2c14217bef0fd6e2a139c57777b4

2024-05-15 13:22 UTC, Emile-Muller commented on Makefile
Tâche ajoutée dans le `make help`: 0bbdb99cb345b3564a79e165445316bdd965872e

2024-05-15 21:30 UTC, J-Christophe requested changes

2024-05-15 21:30 UTC, J-Christophe commented on tests/planet_crs_registry_test.py
si je fais : 
- make install-dev // pour installer les dépendances pour le dev
- make tests => j'ai une erreur

Je viens de remarquer que http://localhost:8080/ws/IAU/2015/51010 retourne cette erreur:
{"detail":"Error when retrieving IAU:2015:51010 as GML - Error: File 'IAU_2015_51010' not found."}
alors que http://localhost:8080/web/search?search_term_kw=51010 fonctionne

Pourrais-tu ajouter un test stp qui boucle sur l'ensemble des CRS et qui vérifie que la conversion GML ne retourne pas une erreur ?

2024-05-15 21:54 UTC, J-Christophe requested changes

2024-05-15 21:54 UTC, J-Christophe commented on docker/Dockerfile
Mon image docker est auto-suffisante à elle-même. C'est à dire qu'un administrateur à besoin seulement de cette image docker (sans code annexe) pour réinstaller le logiciel
Si tu suis les instructions de l'image Docker, la conversion GML ne fonctionnera pas car : 
1/ je récupère le code du GIT 
2/ des variables d'environnement sont utilisées
3/ on lance le logiciel

Si tu essayes ensuite d'accéder à l'URL des GML, cela ne fonctionnera pas car les GML n'ont pas été générés. Il faudrait ajouter le make generate-gml dans le docker après le make avec un && pour éviter de recréer une layer docker supplémentaire. En ravanche, lorsque j'ai fait make generate-gml, j'ai une invite shell qui me demande "Do you have a local installation of Apache SIS? (yes/y/no/n):" : il fraudrait avoir un mode silent qui dit "n" sinon on ne pourra pas créer l'image.

Et bien sûr, il faut modifier le GML_PATH=/planet_crs_registry/data/gml car celui-ci ne va pas fonctionner.

2024-05-16 07:11 UTC, Emile-Muller commented on docker/Dockerfile
Le script de génération de GML est complément indépendant du serveur de CRS Registry.

L'idée c'est de lancer la génération une seule fois et de push les GML générés sur le GitHub (dans `/data/gml`).

Nous avons décidé de mettre le script de génération dans le même dépot GitHub pour que vous ce soit plus pratique pour vous si jamais vous voulez **re-générer** tous les GML.  Ca pourrait servir si jamais ApacheSIS est mis à jour sur la conversion "WKT vers GML".

Donc la tâche `make generate-gml` ne sera pas exécutée au moment où le serveur est lancé.

2024-05-16 07:33 UTC, Emile-Muller commented on tests/planet_crs_registry_test.py
C'est normal que certains GML ne soit pas encore générés, c'est en rapport avec les problématiques qu'a soulevé Martin par mail.

Actuellement avec la dernière version (pas la V1.4, celle sur [GitHub](https://github.com/apache/sis)) d'ApacheSIS, nous avons les 3 problématiques suivantes pour la génération de GML:
```
Java error: Le paramètre « Longitude of natural origin » est inattendu.

Java error: La valeur ‘semiMinorAxis’ = -0,999999999999779 n’est pas valide. On attendait un nombre positif non-nul.

Java error: Il manque une composante « Ellipsoid » dans l’élément « DATUM ».
```

* Pour: ` Longitude of natural origin ` -> évoqué par Martin dans un mail du 30 avril 2024
* Pour: `‘semiMinorAxis’ = -0,999999999999779` -> évoqué par Martin dans un mail du 15 mai 2024
* Pour: ` Ellipsoid dans l’élément DATUM ` -> la réponse de Martin : 
```
Il n'y a pas de GML pour les ellipsoïdes triaxiaux.
TRIAXIAL est un élement qui a été ajouté dans ISO 19111:2019, dont je suis en train de faire la mise-à-jour.
Mais GML ne supporte pas cet élément, donc on aura un problème de toute façon.
```

2024-05-16 09:04 UTC, Emile-Muller commented on tests/planet_crs_registry_test.py
Function de test pour la génération de GML ajoutée: 4554d3d95a54ac12afc39df41db773bf8863a6ef

`make tests` changé en `make test`

2024-05-16 09:28 UTC, Emile-Muller commented
Autre point : pour la partie `RUN` du Dockerfile, je pense qu'il est plus approprié de copier les fichiers locaux plutôt que de cloner le dépôt git. Cela permet de plus facilement tester des changements lorsque l'on modifie le code source. Et on effectue déjà `git clone git://github.com/pdssp/planet_crs_registry` avant de build et déployer CRS Registry.

En somme, remplacer:
```
    ...
    git clone "https://github.com/pdssp/planet_crs_registry.git" && \
    cd planet_crs_registry && \
    ...
```
par:
```
...
COPY . /planet_crs_registry
RUN cd planet_crs_registry && \
...
```

2024-05-22 22:34 UTC, J-Christophe commented on tests/planet_crs_registry_test.py
Emile,

Je ne comprends pas le problème pour le 51010 : 

<pre>
PROJCRS["Lysithea (2015) - Sphere / Ocentric/ Equirectangular, clon = 0",
    BASEGEOGCRS["Lysithea (2015) - Sphere / Ocentric",
        DATUM["Lysithea (2015) - Sphere",
    	ELLIPSOID["Lysithea (2015) - Sphere", 12000, 0,
		LENGTHUNIT["metre", 1, ID["EPSG", 9001]]]],
    	PRIMEM["Reference Meridian", 0,
            ANGLEUNIT["degree", 0.0174532925199433, ID["EPSG", 9122]]],
        ID["IAU", 51000, 2015]],
    CONVERSION["Equirectangular, clon = 0",
        METHOD["Equidistant Cylindrical",
            ID["EPSG", 1028]],
        PARAMETER["Latitude of 1st standard parallel", 0,
            ANGLEUNIT["degree",0.0174532925199433,ID["EPSG", 9122]],
            ID["EPSG", 8823]],
		PARAMETER["Longitude of natural origin", 0,
            ANGLEUNIT["degree",0.0174532925199433,ID["EPSG", 9122]],
            ID["EPSG", 8802]],
		PARAMETER["False easting", 0,
            LENGTHUNIT["metre",1,ID["EPSG", 9001]],
            ID["EPSG", 8806]],
		PARAMETER["False northing", 0,
            LENGTHUNIT["metre",1,ID["EPSG", 9001]],
            ID["EPSG", 8807]]],
    CS[Cartesian, 2],
        AXIS["Easting (E)", east,
            ORDER[1],
            LENGTHUNIT["metre", 1]],
        AXIS["Northing (N)", north,
            ORDER[2],
            LENGTHUNIT["metre", 1]],
    ID["IAU", 51010, 2015]]

2024-05-22 22:38 UTC, J-Christophe commented on docker/Dockerfile
ok ça me va. Tu me feras un commit dans /data/gml une fois que tout sera OK stp

2024-05-22 22:53 UTC, J-Christophe commented
> Autre point : pour la partie `RUN` du Dockerfile, je pense qu'il est plus approprié de copier les fichiers locaux plutôt que de cloner le dépôt git. Cela permet de plus facilement tester des changements lorsque l'on modifie le code source. Et on effectue déjà `git clone git://github.com/pdssp/planet_crs_registry` avant de build et déployer CRS Registry.
> 
> En somme, remplacer:
> 
> ```
>     ...
>     git clone "https://github.com/pdssp/planet_crs_registry.git" && \
>     cd planet_crs_registry && \
>     ...
> ```
> 
> par:
> 
> ```
> ...
> COPY . /planet_crs_registry
> RUN cd planet_crs_registry && \
> ...
> ``

Si je compare les 2 méthodes

### Copier les fichiers locaux :
**Avantages** : Simplifie le processus de test pour les modifications apportées au code source, car il n'est pas nécessaire de cloner à nouveau le dépôt Git.
**Inconvénients** : Les modifications apportées aux fichiers locaux peuvent ne pas être synchronisées avec le dépôt Git distant, ce qui peut créer des incohérences. De plus, cette méthode peut rendre difficile le partage de l'environnement de développement avec d'autres membres de l'équipe ou d'autres machines.

### Cloner le dépôt Git pour générer l'image Docker :
**Avantages** : Garantit que le code utilisé pour générer l'image Docker est synchronisé avec le dépôt Git distant, ce qui évite les incohérences et facilite le partage de l'environnement de développement. Le dockerfile est complètement autonome
**Inconvénients** : Peut nécessiter plus de temps pour tester les modifications apportées au code source, car il faut cloner à nouveau le dépôt Git.

### Conclusion
Si l'objectif est de faciliter la collaboration, le partage et la reproductibilité de l'environnement de développement, le choix le plus judicieux est de cloner le dépôt Git pour générer l'image Docker à mon avis. Cela garantit que tous les membres de l'équipe travaillent avec la même version du code et permet de mieux gérer les modifications apportées. Toutefois, si la priorité est de tester rapidement les modifications apportées au code source sans souci de collaboration ou de partage, je suis d'accord avec toi.

Es-tu d'accord avec cette analyse ? Je suis plutôt pour s'assurer de la qualité du build et que le build soit indépendant de l'environnement de dev

Tu as une idée d'une méthode qui fusionne les 2 méthodes ?

A+

`

2024-05-23 07:08 UTC, Emile-Muller commented
> > Autre point : pour la partie `RUN` du Dockerfile, je pense qu'il est plus approprié de copier les fichiers locaux plutôt que de cloner le dépôt git. Cela permet de plus facilement tester des changements lorsque l'on modifie le code source. Et on effectue déjà `git clone git://github.com/pdssp/planet_crs_registry` avant de build et déployer CRS Registry.
> > En somme, remplacer:
> > ```
> >     ...
> >     git clone "https://github.com/pdssp/planet_crs_registry.git" && \
> >     cd planet_crs_registry && \
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > par:
> > ```
> > ...
> > COPY . /planet_crs_registry
> > RUN cd planet_crs_registry && \
> > ...
> > ``
> > ```
> 
> Si je compare les 2 méthodes
> ### Copier les fichiers locaux :
> 
> **Avantages** : Simplifie le processus de test pour les modifications apportées au code source, car il n'est pas nécessaire de cloner à nouveau le dépôt Git. **Inconvénients** : Les modifications apportées aux fichiers locaux peuvent ne pas être synchronisées avec le dépôt Git distant, ce qui peut créer des incohérences. De plus, cette méthode peut rendre difficile le partage de l'environnement de développement avec d'autres membres de l'équipe ou d'autres machines.
> ### Cloner le dépôt Git pour générer l'image Docker :
> 
> **Avantages** : Garantit que le code utilisé pour générer l'image Docker est synchronisé avec le dépôt Git distant, ce qui évite les incohérences et facilite le partage de l'environnement de développement. Le dockerfile est complètement autonome **Inconvénients** : Peut nécessiter plus de temps pour tester les modifications apportées au code source, car il faut cloner à nouveau le dépôt Git.
> ### Conclusion
> 
> Si l'objectif est de faciliter la collaboration, le partage et la reproductibilité de l'environnement de développement, le choix le plus judicieux est de cloner le dépôt Git pour générer l'image Docker à mon avis. Cela garantit que tous les membres de l'équipe travaillent avec la même version du code et permet de mieux gérer les modifications apportées. Toutefois, si la priorité est de tester rapidement les modifications apportées au code source sans souci de collaboration ou de partage, je suis d'accord avec toi.
> 
> Es-tu d'accord avec cette analyse ? Je suis plutôt pour s'assurer de la qualité du build et que le build soit indépendant de l'environnement de dev
> 
> Tu as une idée d'une méthode qui fusionne les 2 méthodes ?
> 
> A+
> 
> `

Tout ça me semble cohérent.

Je peux proposer un entre-deux:
* On garde le `Dockerfile` actuellement en tant que tel (avec le `git clone`)
* Et je rajoute un `Dockerfile-dev` (avec `COPY . /planet_crs_registry`)

De cette manière, le déploiement actuel ne change pas et le déploiement en dev sera simplifié.

2024-05-23 08:34 UTC, desruisseaux commented on tests/planet_crs_registry_test.py
Il ne devrait pas y avoir de problème avec cette projection. Est-ce que tu observe un message d'erreur?

2024-05-23 13:28 UTC, J-Christophe approved these changes

2024-05-23 13:28 UTC, merged